title: Denis Tsvikevich's Blog
author:
  name: Denis Tsvikevich
  twitter: argohoism
  github: danielargent
  email: dtsvikevich@gmail.com
description: >-
  Welcome to my personal blog about IT, web and others topics!
baseurl: "/blog"
url: "https://danielargent.github.io"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
  style: compressed

exclude: [vendor]