title: Denis Tsvikevich's Blog
author:
  name: Denis Tsvikevich
  twitter: agroholism
  github: danielargent
  email: dtsvikevich@gmail.com
  email-alt: dtsvikevich@mail.ru
description: >-
  Welcome to my personal blog about IT, web and others topics!
baseurl: "/blog"
url: "https://dtsvikevich.ru"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
  style: compressed

exclude: [vendor]